# configs/fast_preview.yaml
# Fast Preview Configuration for Testing

model_dir: "./models"
output_dir: "./output_preview"

num_images: 50
train_test_val_split: [0.8, 0.1, 0.1]
max_objects_per_scene: 2
random_seed: 123

physics:
  gravity: [0.0, 0.0, -9.81]
  simulation_steps: 60
  substeps: 5
  friction: 0.5
  restitution: 0.3

render:
  engine: "EEVEE"  # Faster rendering engine
  samples: 32  # Fewer samples for speed
  use_gpu: true
  resolution: [1280, 720]  # Lower resolution
  file_format: "JPEG"
  quality: 85

randomization:
  lighting_intensity_range: [800.0, 1200.0]
  lighting_color_temp_range: [4000.0, 5000.0]
  camera_distance_range: [0.8, 1.2]
  camera_angle_range: [-15.0, 15.0]
  object_scale_range: [0.9, 1.1]
  background_brightness_range: [0.8, 0.9]

annotation:
  format: "yolo"
  min_visibility: 0.3
  min_bbox_area: 50
  class_names:
    - "ulu"
    - "mask"
  